name: lint-pack

on:
  pull_request:
    branches:
      - main

jobs:
  lint-pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Setup .NET tools
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet restore

      - name: Lint
        run: dotnet fantomas --check --recurse .

      - name: Pack
        run: dotnet pack
